[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "predictionguard"
authors = [
    {name = "Jacob Mansdorfer", email = "jacob@predictionguard.com"},
    {name = "Daniel Whitenack", email = "dan@predictionguard.com"}
    ]
description = "The official Prediction Guard Python SDK"
description-file = "README.md"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version"]
dependencies = [
    "tabulate>=0.10.0,<1",
    "requests>=2.34.2,<3",
]

[tool.uv]
exclude-newer = "2026-07-31T12:33:43.000+00:00"
#exclude-newer-package = { idna = "2026-05-13T19:45:44.44Z", markupsafe = false }

[tool.uv.pip]
require-hashes = true

[project.urls]
Homepage = "https://predictionguard.com"
Documentation = "https://predictionguard.github.io/python-client/"
Repository = "https://github.com/predictionguard/python-client.git"
Issues = "https://github.com/predictionguard/python-client/issues"

[project.optional-dependencies]
dev = [
    "pytest==9.1.1",
    "ruff==0.16.1",
    "sphinx==9.1.0",
    "sphinx-autodoc-typehints==3.13.0",
    "sphinx_rtd_theme==3.1.0",
    "black==26.5.1",
]

[tool.hatch.version]
path = "predictionguard/version.py"